// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEtbNDhXc4TUj-Inaz0ZGw7Frmodiw6o8',
    appId: '1:677163099192:android:08d97636c3b85ff66bf2cd',
    messagingSenderId: '677163099192',
    projectId: 'mainor2023notes-b1c9a',
    databaseURL: 'https://mainor2023notes-b1c9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mainor2023notes-b1c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhrQUCNrVwfGiSveRei5-vES4EgaLjNfI',
    appId: '1:677163099192:ios:9cb07d158b2b71d86bf2cd',
    messagingSenderId: '677163099192',
    projectId: 'mainor2023notes-b1c9a',
    databaseURL: 'https://mainor2023notes-b1c9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mainor2023notes-b1c9a.appspot.com',
    iosClientId: '677163099192-8otl0i2d7m2jpk65pmevsk9k57hk4qc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoProject',
  );
}
